### ISSUE TITLE
NUID is generating non printable characters sometimes

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/jnats#20]
I am using NUID in one of the project as a replacement for UUID. I noticed that at times it is generating non printable characters. Is this by design?

**Comment by mcqueary** [comment]
Definitely not by design. Are you using the latest snapshot?

On Thursday, April 28, 2016, Sachin Walia <notifications@github.com> wrote:

> I am using NUID in one of the project as a replacement for UUID. I noticed
> that at times it is generating non printable characters. Is this by design?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/jnats/issues/20>
>


-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by sachinwalia2k8** [comment]
Thanks @mcqueary for quick response. I'll try the latest snapshot today and will let you know if it is still happening.

**Comment by mcqueary** [comment]
Thanks. I'll also take a look at the code.

On Thu, Apr 28, 2016 at 4:29 PM, Sachin Walia <notifications@github.com>
wrote:

> Thanks @mcqueary <https://github.com/mcqueary> for quick response. I'll
> try the latest snapshot today and will let you know if it is still
> happening.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/jnats/issues/20#issuecomment-215582292>
>



-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by mcqueary** [comment]
Sachin, did you run into this problem again with the latest snapshot?

**Comment by mcqueary** [comment]
Sachin, if you can provide an MVCE or details that might help reproduce this, we can revisit.
