### ISSUE TITLE
About Basic Usage

### ISSUE THREAD

**Issue by simon-miao** [nats-io/jnats#22]
I want to run the Basic Usage, but It's not a java app, can you tell me how to runt it?

Thanks.

**Comment by simon-miao** [comment]
nc.subscribe("foo", m -> {
    System.out.println("Received a message: %s\n", new String(m.Data));
});

**Comment by mcqueary** [comment]
That's a lambda expression requiring Java 8.

On Monday, May 16, 2016, simon-miao <notifications@github.com> wrote:

> nc.subscribe("foo", m -> {
> System.out.println("Received a message: %s\n", new String(m.Data));
> });
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/jnats/issues/22#issuecomment-219611517>
>


-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by simon-miao** [comment]
Thanks for your answer.
