### ISSUE TITLE
Refactor createConn() to handle mock injection better

### ISSUE THREAD

**Issue by mcqueary** [nats-io/jnats#37]
`ConnectionImpl#createConn()` should unconditionally produce a new TCPConnection instance. Currently it checks for `this.conn == null` to determine whether a TCPConnection has been injected (i.e. a mock), or it needs to create a new TCPConnection. This logic interferes with the way the reconnect sequence works for TLS connections. `createConn()` 

`createConn()` should call a static factory method to create a new TCPConnection, thereby leaving implementation details, including whether or not a new object is actually created, to the implementing subclass.

**Comment by pires** [comment]
Refs #32
