### ISSUE TITLE
Release on Maven Central

### ISSUE THREAD

**Issue by oscerd** [nats-io/jnats#4]
Hi,

When do you plan to release jnats on Maven Central?

Thanks

**Comment by pires** [comment]
@oscerd [already is](https://github.com/nats-io/jnats#maven-central). There hasn't been any stable release yet so you have to do with snapshots for now.

**Comment by oscerd** [comment]
thanks @pires 

I mean a stable version.

**Comment by mcqueary** [comment]
A stable release will be posted today.

**Comment by oscerd** [comment]
Thanks @pires and @mcqueary

**Comment by mcqueary** [comment]
Hi, 0.3.1 is now available via Maven Central: http://search.maven.org/#artifactdetails%7Cio.nats%7Cjnats%7C0.3.1%7C

Just add this to your POM:
```xml
<dependency>
    <groupId>io.nats</groupId>
    <artifactId>jnats</artifactId>
    <version>0.3.1</version>
</dependency>
```

**Comment by oscerd** [comment]
Hi @mcqueary 

Many thanks :-)
