### ISSUE TITLE
Connection scope

### ISSUE THREAD

**Issue by prophe05** [nats-io/jnats#44]
What is the best practice for connection lifecycle management? Should I create connection per thread, or per application for example?

**Comment by aricart** [comment]
Can you describe why you think you need multiple connections?

Connections have additional overhead and bookkeeping. One simple example is the NATS protocol will test to see if the client is 'alive'.

Unless there's some very specific need or situation, likely you'll only require a single connection. With that said, it may be useful to have two connections as a way of controlling a process via a separate channel. One connection to handle the application specific data, and one to implement things like application or process management.

In terms of scaling usually adding more applications to handle volume using queuing where the NATS server distributes messages between the clients is a better overall strategy. Binding connections at the thread level is likely something you don't ever want to do, unless you have very specific needs and are keeping an exact handle on the number of connections you are using.

If you describe your needs we may be able to comment more fully.

**Comment by prophe05** [comment]
One connection per application is my case!) But I worry about threadsafty, when nats connection is a shared resource!

Thank you for your response!
