### ISSUE TITLE
jnats 0.5.0 and 0.5.1-Snapshot error with gnatsd 0.9.4

### ISSUE THREAD

**Issue by kcarlson2915** [nats-io/jnats#54]
Connection to 0.9.4 server using a String array of 3 elements with the format [nats://(IP):4222,nats://(IP):4222,nats://(IP):4222] throws the attached stacktrace. The same code running with the 0.8.1 server functions as expected.
![screen shot 2016-08-19 at 10 24 43 am](https://cloud.githubusercontent.com/assets/2475661/17818179/3cade176-65f7-11e6-84ff-fa0d0cd323d0.png)

**Comment by mcqueary** [comment]
Hi, can you give me the exact INFO string your client is receiving? One easy way to get that is to `telnet <your NATS node IP> <your port>`, and just cut and paste the exact string here.

This should be fixed in 0.5.1, so I'd like to see what I missed :) Thanks!

**Comment by kcarlson2915** [comment]
{"server_id":"W2v6Vo9KOOq4Ujc5lKL0Sx","version":"0.9.4","go":"go1.6.3","host":"10.21.2.87","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576,"connect_urls":["10.21.2.95:4222","10.21.2.105:4222"]}

**Comment by mcqueary** [comment]
Thanks Kevin, I'll have a look right now.

**Comment by mcqueary** [comment]
@kcarlson2915 Kevin, can you verify that you're actually testing this against the 0.5.1-SNAPSHOT? I can reproduce that exception with 0.5.0 (which I expect), but am unable to reproduce that exception using 0.5.1-SNAPSHOT.

**Comment by kcarlson2915** [comment]
Snapshot appears to be working correctly. Early morning mistakes I guess, but thanks for taking the time to look at it.

**Comment by mcqueary** [comment]
My pleasure! Actually, I'm happy to know somebody else is banging on my fix before I release it :)
